#!/bin/bash

#VARIABLES

#Kubernetes namespace for CloudBees CI
namespace=cloudbees-core

#Name of the Operations Center or Controller statefulset
instanceStatefulsetName=example-controller

#Container with version if required, to use for the rescue pod
rescueContainerImage=governmentpaas/awscli

#Source of backup artefacts. Supports "local" or "s3"
backupSource=local

#Path to backup file sourced locally
backupFilePath=/tmp/backup.tar.gz

#Download the backup artifact from AWS S3
s3BucketName=cb-ci-backups
s3FilePath=controller/backup.tar.gz
cloudLocalDownloadDir=/tmp
